server:
  port: 8083
spring:
  datasource:
    url: jdbc:mysql://localhost:3306/ego?serverTimezone=UTC
    driver-class-name: com.mysql.jdbc.Driver
    username: root
    password: root
    hikari:
      maximum-pool-size: 20
      minimum-idle: 10
mybatis:
  type-aliases-package: com.ego.demo.userservicedemo.pojo


